export enum ActivityType {
  // 인증
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  REGISTER = 'REGISTER',

  // 리뷰
  REVIEW_CREATE = 'REVIEW_CREATE',
  REVIEW_UPDATE = 'REVIEW_UPDATE',
  REVIEW_DELETE = 'REVIEW_DELETE',
  REVIEW_REACTION = 'REVIEW_REACTION',
  REVIEW_VIEW = 'REVIEW_VIEW',

  // 중고 도서
  SALE_CREATE = 'SALE_CREATE',
  SALE_UPDATE = 'SALE_UPDATE',
  SALE_DELETE = 'SALE_DELETE',
  SALE_STATUS_CHANGE = 'SALE_STATUS_CHANGE',
  SALE_VIEW = 'SALE_VIEW',

  // 독서 기록
  READING_LOG_CREATE = 'READING_LOG_CREATE',
  READING_LOG_UPDATE = 'READING_LOG_UPDATE',
  READING_LOG_DELETE = 'READING_LOG_DELETE',
  READING_LOG_KONG = 'READING_LOG_KONG',

  // 댓글
  COMMENT_CREATE = 'COMMENT_CREATE',
  COMMENT_UPDATE = 'COMMENT_UPDATE',
  COMMENT_DELETE = 'COMMENT_DELETE',
  COMMENT_LIKE = 'COMMENT_LIKE',

  // 도서 (비로그인 추적 포함)
  BOOK_SEARCH = 'BOOK_SEARCH',
  BOOK_VIEW = 'BOOK_VIEW',

  // AI (LLM)
  LLM_BOOK_SUMMARY = 'LLM_BOOK_SUMMARY',

  // 사용자
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  WISHLIST_ADD = 'WISHLIST_ADD',
  WISHLIST_REMOVE = 'WISHLIST_REMOVE',
  ACCOUNT_DELETE = 'ACCOUNT_DELETE',
}
