export const API_PATHS = {
  auth: {
    login: (provider: "naver") => `/auth/${provider}`,
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    exchange: "/auth/exchange",
    emailRegister: "/auth/signup",
    emailLogin: "/auth/login",
    sendVerificationEmail: "/auth/send-verification-email",
    verifyEmail: "/auth/verify-email",
  },

  user: {
    base: "/user",
    me: "/user/me",
    profile: "/user/profile",
    publicProfile: (handle: string) => `/user/profile/${handle}`,
    stats: "/user/stats",
    wishlist: "/user/wishlist",
    wishlistCheck: "/user/wishlist/check",
    wishlistStatus: "/user/wishlist/status",
    checkNickname: "/user/check-nickname",
  },
  book: {
    list: "/book/external/list",
    detail: "/book/external/detail",
    sales: "/book/sales",
    sale: "/book/sale",
    mySales: "/user/my-sales",
    saleStatus: (saleId: number) => `/book/sales/${saleId}/status`,
    saleDetail: (saleId: string) => `/book/sales/${saleId}`,
    saleForEdit: (saleId: string | number) => `/book/sales/${saleId}/edit`,
    relatedSales: (isbn: string) => `/book/${isbn}/sales`,
    updateSale: (saleId: number) => `/book/sales/${saleId}`,
    deleteSale: (saleId: number) => `/book/sales/${saleId}`,
    recentSales: "/book/sales/recent",
    regions: "/book/sales/regions",
    popularBooks: "/book/popular",
    recordView: (isbn: string) => `/book/${isbn}/view`,
    recordSaleView: (saleId: number) => `/book/sales/${saleId}/view`,
    popularSales: "/book/sales/popular",
    stats: (isbn: string) => `/book/${isbn}/stats`,
  },
  searchKeyword: {
    record: "/search-keywords",
    popular: "/search-keywords/popular",
  },
  llm: {
    summary: "/llm/book-summary",
    getSummary: (isbn: string) => `/llm/book-summary/${isbn}`,
  },
  chat: {
    rooms: "/chat/rooms",
    room: (roomId: number) => `/chat/rooms/${roomId}`,
    messages: (roomId: number) => `/chat/rooms/${roomId}/messages`,
    read: (roomId: number) => `/chat/rooms/${roomId}/read`,
  },
  comment: {
    base: "/comments",
    my: "/comments/my",
    detail: (id: number) => `/comments/${id}`,
    like: (id: number) => `/comments/${id}/like`,
  },
  notification: {
    base: "/notifications",
    read: (id: number) => `/notifications/${id}/read`,
    readAll: "/notifications/read-all",
    unreadCount: "/notifications/unread-count",
  },
  readingLog: {
    base: "/reading-logs",
    stats: "/reading-logs/stats",
    list: "/reading-logs/list",
    stack: "/reading-logs/stack",
    /** 공개 프로필의 독서 키재기. 독서 기록이 비공개면 빈 목록 */
    publicStack: (handle: string) => `/reading-logs/users/${handle}/stack`,
    settings: "/reading-logs/settings",
    /** 내가 이 책을 기록한 횟수와 마지막 날짜 */
    bookStatus: (isbn: string) => `/reading-logs/book/${isbn}/status`,
    detail: (id: string) => `/reading-logs/${id}`,
    // ✅ 라운지 API 경로 추가
    loungeFeed: "/reading-logs/lounge",
    loungePopular: "/reading-logs/lounge/popular",
    loungeActiveReaders: "/reading-logs/lounge/active-readers",
    loungeBookReaders: (isbn: string) =>
      `/reading-logs/lounge/book/${isbn}/readers`,
  },
  review: {
    base: "/reviews",
    detail: (id: number | string) => `/reviews/${id}`,
    recordView: (id: number | string) => `/reviews/${id}/view`,
    edit: (id: number | string) => `/reviews/${id}/edit`,
    feeds: "/reviews/feeds",
    tags: "/reviews/tags",
    popular: "/reviews/popular",
    recommend: (id: number | string) => `/reviews/${id}/recommend`,
    myReaction: (id: number | string) => `/reviews/${id}/reaction`,
    toggleReaction: (id: number | string) => `/reviews/${id}/reactions`,
  },
  insights: {
    base: "/insights",
    locationSales: "/insights/location-sales",
  },
  search: {
    ai: "/search/ai",
    aiStream: "/search/ai/stream",
  },
  order: {
    base: "/orders",
    cancelSelection: (orderNumber: string) =>
      `/orders/${orderNumber}/selection`,
    pay: (orderNumber: string) => `/orders/${orderNumber}/pay`,
    ship: (orderNumber: string) => `/orders/${orderNumber}/ship`,
    confirm: (orderNumber: string) => `/orders/${orderNumber}/confirm`,
    dispute: (orderNumber: string) => `/orders/${orderNumber}/dispute`,
    cancel: (orderNumber: string) => `/orders/${orderNumber}/cancel`,
    myPurchases: "/orders/my-purchases",
    mySales: "/orders/my-sales",
    detail: (orderNumber: string) => `/orders/${orderNumber}`,
    byRoom: (roomId: number) => `/orders/by-room/${roomId}`,
  },
  trade: {
    reservation: (saleId: number) => `/trades/sales/${saleId}/reservation`,
    completion: (saleId: number) => `/trades/sales/${saleId}/completion`,
    candidates: (saleId: number) => `/trades/sales/${saleId}/candidates`,
    myCompletions: "/trades/completions/my",
    completionByRoom: (roomId: number) =>
      `/trades/completions/by-room/${roomId}`,
    completionDetail: (completionId: number) =>
      `/trades/completions/${completionId}`,
  },
  tradeReview: {
    base: "/trade-reviews",
    detail: (reviewId: number) => `/trade-reviews/${reviewId}`,
    userReviews: (handle: string) => `/trade-reviews/user/${handle}`,
    sellerStats: (handle: string) => `/trade-reviews/user/${handle}/stats`,
    eligibility: (completionId: number) =>
      `/trade-reviews/eligibility/${completionId}`,
  },
};
