export const PATHS = {
  HOME: "/",
  LOUNGE: "/lounge",
  LOGIN: "/login",
  SIGNUP: "/signup",
  VERIFY_EMAIL: "/verify-email",
  CALLBACK: "/callback",
  BOOK_SEARCH: "/book/search",
  BOOK_DETAIL: (isbn: string) => `/book/${isbn}/detail`,
  BOOK_SALES_REGISTER: "/book/sales/register",
  BOOK_SALES_DETAIL: (id: string | number) => `/book/sales/${id}`,
  MY_PAGE_SALES: "/my-page/sales",
  MY_PAGE_TRADES: "/my-page/trades",
  MY_PAGE_SALES_EDIT: (id: string | number) => `/my-page/sales/${id}/edit`,
  REVIEWS: "/book/reviews",
  REVIEWS_BY_TAG: (tag: string) =>
    `/book/reviews?tag=${encodeURIComponent(tag)}`,
  REVIEWS_BY_ISBN: (isbn: string) =>
    `/book/reviews?isbn=${encodeURIComponent(isbn)}`,
  REVIEW_WRITE: "/book/reviews/write",
  REVIEW_DETAIL: (id: string | number) => `/book/reviews/${id}`,
  REVIEW_EDIT: (id: string | number) => `/book/reviews/${id}/edit`,
  MY_PAGE: "/my-page",
  MY_REVIEWS: "/my-page/reviews",
  MY_COMMENTS: "/my-page/comments",
  MY_PAGE_WISHLIST: "/my-page/wishlist",
  BOOK_MARKET: "/book/market",
  USER_PROFILE: (handle: string) => `/users/${handle}`,
  /** 카드덱 공유 링크(폐지). 옛 링크를 프로필로 보내는 라우트만 남았다 */
  SHARE_DECK: (handle: string) => `/share/deck/${handle}`,
  INSIGHTS: "/insights",
  READING_LOG: "/my-page/reading-log",
  /** 독서 키재기 공개 소개(검색 유입용) */
  READING_HEIGHT: "/reading-height",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  ORDER_PAYMENT: (orderId: string | number) => `/order/payment/${orderId}`,
  ORDER_PAYMENT_SUCCESS: "/order/payment/success",
  ORDER_PAYMENT_FAIL: "/order/payment/fail",
  ORDER_DETAIL: (orderId: string | number) => `/order/${orderId}`,
  MY_PAGE_PURCHASES: "/my-page/purchases",
  MY_PAGE_SALES_ORDERS: "/my-page/sales-orders",
} as const;
